---
- name: uri module demo
  hosts: all
  become: false
  vars:
    server: "https://10.128.88.10:9000"
    endpoint: "/auth"
  tasks:
    - name: list users
      ansible.builtin.uri:
        url: "{{ server }}{{ endpoint }}"
        method: GET
        status_code: 200
        timeout: 30
      register: result

    - name: debug
      ansible.builtin.debug:
        var: result.json.data
