- name: Using a REST API
  become: false
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: “Let’s call an API”
    - uri: 
        method: POST
        url: https://10.128.88.10:9443/auth/
        return_content: yes
        body: {
                "password": "PortainerUser_Password",
                "username": "{{PortainerUser_Account}}"}
        body_format: json
        status_code: 204

