- name: Using a REST API
  become: false
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: “Let’s call an API”
    - uri: 
        method: POST
        url: http://10.128.88.10:9443/auth/
        url_password: "TEST"
        url_password: "TEST"
        return_content: yes
        body: {"configure":".*","write":".*","read":".*"}
        body_format: json
        status_code: 204

