- name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
  ansible.builtin.uri:
    url: http://10.128.88.10:9000
    return_content: yes
  register: this
  failed_when: "'AWESOME' not in this.content"
