- name: Using a REST API
  become: false
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: “Let’s call an API”


- name: Everyone loves a good Chuck Norris joke
  uri:
    url: https://10.128.88.10:9443/auth
    method: GET

- name: Login to an API
  uri:
    url: https://10.128.88.10:9443/auth
    method: POST
    body_format: json
    body:
      name: your_username
      password: your_password
      client_id: YOUR_CLIENT_ID
      access_token: ACCESS_TOKEN
      connection: CONNECTION
      scope: SCOPE
