- name: Using a REST API
  become: false
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: “Let’s call an API”
    - uri: 
        method: POST
        url: https://S-600-ITx-050.tphh.corp:9443/auth/
        return_content: yes
        body: {
                "password": "{{PortainerUser_Password}}",
                "username": "{{PortainerUser_Account}}"}
        body_format: json
        status_code: 204
      register: response
      until: response.json.status == "UP"
      retries: 10
      delay: 30


