- name: Using a REST API
  become: false
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: “Let’s call an API”
    - uri: 
        url: "https:/10.128.88.10:9443/auth"
        method: POST
        return_content: yes
        HEADER_Content-Type: "application/json"
        body: "{{ lookup('file','create_body.json') | to_json }}"



